#!/bin/sh

if [[ -f /etc/gdm3/daemon.conf ]]; then
sed -i 's/#WaylandEnable=false/WaylandEnable=false/' /etc/gdm3/daemon.conf
sed -i 's/WaylandEnable=false/WaylandEnable=false/' /etc/gdm3/daemon.conf
sed -i 's/#WaylandEnable=true/WaylandEnable=false/' /etc/gdm3/daemon.conf
sed -i 's/WaylandEnable=true/WaylandEnable=false/' /etc/gdm3/daemon.conf
fi
if [[ -f /etc/gdm3/custom.conf ]]; then
sed -i 's/#WaylandEnable=false/WaylandEnable=false/' /etc/gdm3/custom.conf
sed -i 's/WaylandEnable=false/WaylandEnable=false/' /etc/gdm3/custom.conf
sed -i 's/#WaylandEnable=true/WaylandEnable=false/' /etc/gdm3/custom.conf
sed -i 's/WaylandEnable=true/WaylandEnable=false/' /etc/gdm3/custom.conf
else
echo 'WaylandEnable=false'>/etc/gdm3/custom.conf
fi

mkdir -p /usr/share/e-ag
#chmod 777 /usr/share/e-ag
systemctl daemon-reload || true

systemctl enable e-ag-client-console.service || true
systemctl start e-ag-client-console.service || true

systemctl enable e-ag-client-networkprofil.service || true
systemctl start e-ag-client-networkprofil.service || true
#systemctl enable ssh.service
#systemctl start ssh.service

systemctl enable e-ag-x11vnclogin.service || true
systemctl start e-ag-x11vnclogin.service || true

systemctl enable e-ag-x11vncdesktop.service || true
systemctl start e-ag-x11vncdesktop.service || true

e-ag-client-tray&
exit 0
