#!/bin/sh
systemctl disable e-ag-client-console.service || true
systemctl stop e-ag-client-console.service || true

systemctl disable e-ag-client-networkprofil.service || true
systemctl stop e-ag-client-networkprofil.service || true
#systemctl disable ssh.service
#systemctl stop ssh.service

#systemctl disable vsftpd.service
#systemctl stop vsftpd.service

systemctl disable e-ag-x11vncdesktop.service || true
systemctl stop e-ag-x11vncdesktop.service || true

systemctl disable e-ag-x11vnclogin.service || true
systemctl stop e-ag-x11vnclogin.service || true

systemctl daemon-reload  || true
rm -rf /usr/share/e-ag
exit 0
