#!/bin/sh
if [[ -f /etc/gdm3/daemon.conf ]]; then
sed -i 's/#WaylandEnable=false/WaylandEnable=false/' /etc/gdm3/daemon.conf
sed -i 's/WaylandEnable=false/WaylandEnable=false/' /etc/gdm3/daemon.conf
sed -i 's/#WaylandEnable=true/WaylandEnable=false/' /etc/gdm3/daemon.conf
sed -i 's/WaylandEnable=true/WaylandEnable=false/' /etc/gdm3/daemon.conf
fi
#mkdir /usr/share/e-ag
#chmod 777 /usr/share/e-ag
systemctl daemon-reload || true

systemctl enable ssh.service || true
systemctl start ssh.service || true

systemctl enable vsftpd.service || true
systemctl start vsftpd.service || true

systemctl enable e-ag-x11vnclogin.service || true
systemctl start e-ag-x11vnclogin.service || true

systemctl enable e-ag-x11vncdesktop.service || true
systemctl start e-ag-x11vncdesktop.service || true

systemctl enable e-ag-networkprofil.service || true
systemctl start e-ag-networkprofil.service || true
exit 0
