#!/bin/sh

#systemctl disable ssh.service
#systemctl stop ssh.service

#systemctl disable vsftpd.service
#systemctl stop vsftpd.service

#systemctl disable x11vnc-e-ag.service
#systemctl stop x11vnc-e-ag.service


#rm -rf  /usr/share/e-ag
#chmod 777 /usr/share/e-ag

systemctl disable e-ag-x11vncdesktop.service || true
systemctl stop e-ag-x11vncdesktop.service || true

systemctl disable e-ag-x11vnclogin.service || true
systemctl stop e-ag-x11vnclogin.service || true

systemctl daemon-reload
pkill e-ag-tray
exit 0
