#!/bin/sh

sed -i 's/#WaylandEnable=false/WaylandEnable=false/' /etc/gdm3/daemon.conf
sed -i 's/WaylandEnable=false/WaylandEnable=false/' /etc/gdm3/daemon.conf
sed -i 's/#WaylandEnable=true/WaylandEnable=false/' /etc/gdm3/daemon.conf
sed -i 's/WaylandEnable=true/WaylandEnable=false/' /etc/gdm3/daemon.conf

sed -i 's/AutomaticLogin=ogrenci/#AutomaticLogin=ogrenci/' /etc/gdm3/daemon.conf
sed -i 's/#AutomaticLogin=ogrenci/#AutomaticLogin=ogrenci/' /etc/gdm3/daemon.conf

#mkdir /usr/share/e-ag
#chmod 777 /usr/share/e-ag
systemctl daemon-reload

systemctl enable e-ag-client-console.service
systemctl start e-ag-client-console.service

systemctl enable e-ag-client-networkprofil.service
systemctl start e-ag-client-networkprofil.service
#systemctl enable ssh.service
#systemctl start ssh.service

#systemctl enable vsftpd.service
#systemctl start vsftpd.service

systemctl enable e-ag-x11vnclogin.service
systemctl start e-ag-x11vnclogin.service

systemctl enable e-ag-x11vncdesktop.service
systemctl start e-ag-x11vncdesktop.service
e-ag-client-tray&
exit 0
